language: node_js
node_js:
  - '0.10'
env:
  - noninteractive=true
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y php5
  - sudo apt-get install -y ruby
  - sudo apt-get install -y rubygems
  - rvmsudo gem install compass
  - rvmsudo gem update --system
  - npm install -g grunt-cli
