language: node_js
node_js:
  - '0.10'
env:
  - noninteractive=true
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y php5
  - sudo apt-get install -y ruby-full
  - sudo gem install compass
before_script:
  - npm install -g grunt-cli
