CREATE OR REPLACE FUNCTION US_DESIGN.TSUBL_VALUE (LONGITUDE IN NUMERIC, LATITUDE IN NUMERIC) 
	RETURNS INTEGER AS $$
	DECLARE RETURN_VAL INTEGER;
	BEGIN
		SELECT value INTO RETURN_VAL FROM US_DESIGN.TSUBL WHERE
			SDE.ST_DISJOINT(SHAPE, SDE.ST_POINT($1, $2, 4326))=false
			ORDER BY VALUE DESC;
		RETURN COALESCE(RETURN_VAL,-1);
	END;
$$ LANGUAGE PLPGSQL;
